from pathlib import Path
p=Path('06. Playbooks/IC Project Registry.md')
text=p.read_text(encoding='utf-8')
old="""| Portfolio Mutation Proposal Object and Gated Apply Helper | Finance automation / owner-gated mutation proposals | Veritas | Active - Phase 2 review-only proposal generation | Workflow 56 owns typed review-only proposal objects for sleeve changes, ticker promotion/demotion, and canonical-status moves. Phase 1 provides schema and validator; Phase 2 is now open to generate validated review-only proposal packets under `tmp/portfolio-mutation-proposals/`. | Main-session orchestrated; implementation helper may use medium/high thinking for generators/validators, followed by independent audit | Yes for Phase 1; Phase 2 pending | Portfolio-mutation automation audit was promoted; Phase 1 added `scripts/schemas/portfolio_mutation_proposal_schema.json`, `scripts/portfolio_mutation_proposal_schema_validator.py`, `scripts/test_portfolio_mutation_proposal_schema_validator.py`, and `tmp/portfolio-mutation-proposals/.gitkeep`; audit saved at `08. Audits/WF56 Phase 1 Schema Validator Audit - 2026-05-10.md`. | Build review-only proposal generator with risk/source/owner-conflict/status-tuple checks; defer any dry-run patch helper or write-capable apply helper until Randall approves the scoped helper design. | No for proposal validation/generation; yes for applying weights, cash target, sleeves, promotion/demotion, owner approval state, sizing, risk rules, execution entitlement, canonical status, trades, or account actions | `06. Playbooks/Project Continuity/Workflow 56 - Portfolio Mutation Proposal Object and Gated Apply Helper.md` | `08. Audits/Portfolio Mutation Automation Audit - 2026-05-10.md`; `08. Audits/WF56 Phase 1 Schema Validator Audit - 2026-05-10.md`; `tmp/portfolio-mutation-automation-audit.json` |"""
new="""| Portfolio Mutation Proposal Object and Gated Apply Helper | Finance automation / owner-gated mutation proposals | Veritas | Phase 2 implemented / Phase 3 deferred | Workflow 56 owns typed review-only proposal objects for sleeve changes, ticker promotion/demotion, canonical-status moves, and now capital-deployment recommendation packet conversion. Phase 1 schema/validator and Phase 2 review-only generator are live; apply helpers remain deferred. | Main-session orchestrated; future dry-run/apply-helper design requires separate approval and independent audit | Yes for Phase 1 and Phase 2 generator; no for apply tooling | Phase 2 added/tightened review-only validators, current-window index wiring, and `scripts/portfolio_mutation_proposal_generator.py`; current generated bundle validates cleanly under schema, scope, canonical-status, pro-forma risk, authority vocabulary, and dry-run post-apply checks. | Keep validators green while WF58 uses packets; only design Phase 3 dry-run patch previews if Randall separately approves the scoped helper design. | No for proposal validation/generation; yes for applying weights, cash target, sleeves, promotion/demotion, owner approval state, sizing, risk rules, execution entitlement, canonical status, trades, or account actions | `06. Playbooks/Project Continuity/Workflow 56 - Portfolio Mutation Proposal Object and Gated Apply Helper.md` | `tmp/portfolio-mutation-proposals/current-capital-deployment-recommendations.json`; `tmp/*validation*.json` |"""
if old not in text:
    raise SystemExit('old WF56 row not found')
text=text.replace(old,new)
insert_after=new+'\n'
wf58="""| Dashboard Freshness, Entry Bands, Capital Recommendations, and Discrepancy Automation | Finance automation / dashboard trust and note-canon readiness | Veritas | Active - Phase 1 bones implemented / residual hardening queued | Workflow 58 owns the current priority to make dashboards fresh enough for presentation, bounded canonical-sync review, and review-only capital recommendation packets while starting entry-band and discrepancy automation. Readiness gates, discrepancy resolver, capital-rec generator, current-window indexing, and morning/post-close/Sunday manifest wiring are live; GS eligible band sync was applied, while MSFT/AMD remain manual-review blockers. | Main-session orchestrated; parallel helper lanes appropriate for bounded validators, renderers, cron posture design, and independent QA | Partial - Phase 1 proof-green; residual hardening pending | Proof passed on 2026-05-11/12: source freshness tests, discrepancy resolver tests, capital-rec generator tests, schema/scope/invariant/risk/authority/post-apply validators, run-summary tail test, and morning/post-close/Sunday dry-run manifest checks. | Add capital-rec Markdown and bundle-level validator, harden current-window role tests, decide whether separate cron jobs are needed beyond finance-chain tails, and keep MSFT/AMD in manual-review queue until eligible. | No for presentation/review packet generation; yes for trade/account action, owner-approval inference, portfolio mutation apply, sizing/sleeve/cash/risk-rule changes, execution entitlement, or silent cron canon mutation | `06. Playbooks/Project Continuity/Workflow 58 - Dashboard Freshness Entry Bands Capital Recommendations and Discrepancy Automation.md` | `tmp/dashboard-validation.json`; `tmp/finance-discrepancy-resolver.*`; `tmp/portfolio-mutation-proposals/current-capital-deployment-recommendations.json`; `tmp/current-window-artifacts.*` |"""
marker="| Composite Regime and Sector Positioning PDF Visual Enhancement |"
idx=text.index(marker)
text=text[:idx]+wf58+'\n'+text[idx:]
p.write_text(text,encoding='utf-8')
