"""daily_executive_brief.py

Generate the autonomous Daily Executive Summary from cached tmp/ artifacts.

Reads:
    tmp/market-state.json
    tmp/trigger-sheet.json
    tmp/technical-refresh.json
    tmp/post-earnings-prep.json
    tmp/dashboard-validation.json
    tmp/deployment-check.json
    tmp/earnings-calendar.json
    tmp/dashboard-delta.json
    tmp/band-proposals.json (optional)

Writes:
    01. Dashboards/Daily Executive Summary/YYYY-MM-DD.md
        OR YYYY-MM-DD-machine.md if a session brief already exists
    tmp/daily-executive-brief.json

Behavior:
    - Critical rule: never overwrite a session-written brief. If the canonical
      file exists and was NOT auto-generated by this script, the script writes
      to YYYY-MM-DD-machine.md so the human/agent version takes precedence.
    - Quantitative sections auto-populate. Where judgment is required (regime
      framing, conviction calls), the script emits clear factual statements
      derived from data and explicitly labels anything that is data-driven vs.
      hand-curated.

Usage:
    python scripts/daily_executive_brief.py
"""

from __future__ import annotations

import json
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

from market_data_utils import atomic_write_json, atomic_write_text, canonical_note_mutation_gate

WORKSPACE        = Path(__file__).resolve().parents[1]
MARKET_STATE     = WORKSPACE / "tmp" / "market-state.json"
TRIGGER_SHEET    = WORKSPACE / "tmp" / "trigger-sheet.json"
TECHNICAL        = WORKSPACE / "tmp" / "technical-refresh.json"
POST_PREP        = WORKSPACE / "tmp" / "post-earnings-prep.json"
VALIDATION       = WORKSPACE / "tmp" / "dashboard-validation.json"
DEPLOYMENT       = WORKSPACE / "tmp" / "deployment-check.json"
EARNINGS_CAL     = WORKSPACE / "tmp" / "earnings-calendar.json"
DELTA            = WORKSPACE / "tmp" / "dashboard-delta.json"
BAND_PROPOSALS   = WORKSPACE / "tmp" / "band-proposals.json"
OUT_DIR          = WORKSPACE / "01. Dashboards" / "Daily Executive Summary"
OUT_JSON         = WORKSPACE / "tmp" / "daily-executive-brief.json"


def load_json(path: Path) -> dict | list | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"  WARNING: could not load {path.name}: {exc}")
        return None


def fmt(v: Any, decimals: int = 2, suffix: str = "") -> str:
    if v is None:
        return "N/A"
    try:
        return f"{float(v):,.{decimals}f}{suffix}"
    except Exception:
        return str(v)


def signed_pct(v: Any, decimals: int = 2) -> str:
    if v is None:
        return "N/A"
    try:
        n = float(v)
        sign = "+" if n >= 0 else ""
        return f"{sign}{n:,.{decimals}f}%"
    except Exception:
        return str(v)


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Trust and confidence
# ---------------------------------------------------------------------------

def confidence_grade(validation: dict | None) -> tuple[str, str]:
    """Return (grade, rationale) — grade is one of high/moderate/reduced/critical."""
    if not validation:
        return ("reduced", "validation file missing")
    overall = (validation.get("overall") or "").lower()
    summ = validation.get("summary", {})
    crit = summ.get("critical", 0)
    warn = summ.get("warning", 0)
    if crit > 0:
        return ("critical", f"{crit} critical contradiction(s) on the dashboard")
    if warn == 0:
        return ("high", "no warnings on the dashboard")
    if warn <= 2:
        return ("moderate", f"{warn} warning(s) — usable with caveats")
    return ("reduced", f"{warn} warnings — degraded but usable")


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def section1_bottom_line(trigger: dict, validation: dict, ms: dict) -> str:
    summary = trigger.get("summary", {}) or {}
    deployable = summary.get("deployable_now", []) or []
    almost     = summary.get("almost_deployable", []) or []
    blocked    = summary.get("blocked", []) or []
    do_not     = summary.get("do_not_touch", []) or []

    grade, rationale = confidence_grade(validation)

    lines = ["## 1) Executive bottom line\n"]

    if deployable:
        lines.append(f"**{len(deployable)} name(s) deployable now: {', '.join(deployable)}.**")
    else:
        lines.append("**Nothing is deployable now.**")

    if almost:
        lines.append(f"\n{len(almost)} name(s) almost-deployable, pullback required: **{', '.join(almost)}**.")
    if blocked:
        lines.append(f"\n{len(blocked)} name(s) earnings-blocked: **{', '.join(blocked)}**.")
    if do_not:
        lines.append(f"\n{len(do_not)} name(s) do-not-touch / repair: **{', '.join(do_not)}**.")

    lines.append(f"\nConfidence is **{grade}** — {rationale}.")
    return "\n".join(lines)


def section2_execution_context(ms: dict, validation: dict) -> str:
    data = (ms or {}).get("data", {}) or {}
    fed = data.get("fed", {})
    eq = data.get("equities", {})
    vol = data.get("volatility", {})
    fx = data.get("fx", {})
    en = data.get("energy", {})
    fut = data.get("futures", {}) or {}
    tr = data.get("treasuries", {})

    es = fut.get("spx_futures", {}) or {}
    nq = fut.get("nasdaq_futures", {}) or {}
    last_td = ms.get("last_trading_day", "unknown") if ms else "unknown"
    grade, _ = confidence_grade(validation)

    lines = ["## 2) Execution context\n"]
    lines.append(f"- **Macro readiness:** {grade}.")
    lines.append(f"- **SPX (last close):** {fmt(eq.get('spx'))} as of {eq.get('as_of', last_td)}.")
    lines.append(f"- **VIX:** {fmt(vol.get('vix'))} as of {vol.get('as_of', last_td)}.")
    lines.append(f"- **Rates:** 10Y {fmt(tr.get('10y'), 3)}%, 2Y {fmt(tr.get('2y'), 3)}%, "
                 f"2s10s {fmt(tr.get('curve_2s10s_bps'), 1)} bps.")
    lines.append(f"- **Dollar / energy:** DXY {fmt(fx.get('dxy'))}, Brent ${fmt(en.get('brent'))}, "
                 f"WTI ${fmt(en.get('wti'))}.")

    if es.get("last_price"):
        lines.append(f"- **Directional open read:** ES futures {fmt(es.get('last_price'))} "
                     f"({signed_pct(es.get('change_pct'))}), NQ futures {fmt(nq.get('last_price'))} "
                     f"({signed_pct(nq.get('change_pct'))}). Treat as directional context, not full pre-market tape.")

    target_lo = fed.get("target_low")
    target_hi = fed.get("target_high")
    fomc_date = fed.get("next_fomc_date")
    cut_prob = fed.get("cut_probability_next_meeting")
    fed_line = f"- **Fed:** target {fmt(target_lo, 2)}%–{fmt(target_hi, 2)}%, confirmed {fed.get('target_confirmed','n/a')}."
    if fomc_date:
        cut_str = f"{cut_prob:.0f}% cut prob" if cut_prob is not None else "cut prob unwired"
        fed_line += f" Next FOMC {fomc_date} ({cut_str})."
    lines.append(fed_line)

    return "\n".join(lines)


def section3_what_changed(delta: dict | None) -> str:
    lines = ["## 3) What changed since yesterday\n"]
    if not delta:
        lines.append("- No delta artifact available.")
        return "\n".join(lines)
    if delta.get("first_run"):
        lines.append("- First run — no prior snapshot to compare against.")
        return "\n".join(lines)
    changes = delta.get("changes", []) or []
    if not changes:
        lines.append("- No tracked-name state changes since the last dashboard run.")
        return "\n".join(lines)
    for ch in changes:
        t = ch.get("type", "")
        tk = ch.get("ticker", "")
        if t == "action_state_change":
            lines.append(f"- **{tk}** — action state {ch.get('from','?')} → {ch.get('to','?')}.")
        elif t == "below_stop_entered":
            lines.append(f"- **{tk}** — entered below-stop.")
        elif t == "below_stop_recovered":
            lines.append(f"- **{tk}** — recovered above stop.")
        elif t == "exited_band":
            lines.append(f"- **{tk}** — exited prior entry band.")
        elif t == "entered_band":
            lines.append(f"- **{tk}** — entered entry band.")
        else:
            lines.append(f"- **{tk}** — {t}.")
    if delta.get("summary"):
        lines.append(f"\nDelta summary: {delta['summary']}")
    return "\n".join(lines)


def section4_todays_catalysts(earnings: dict, ms: dict, today: date) -> str:
    lines = ["## 4) Today's catalysts\n"]
    todays: list[str] = []

    for r in (earnings or {}).get("records", []):
        if r.get("error") or not r.get("next_earnings_date"):
            continue
        try:
            ed = datetime.strptime(r["next_earnings_date"], "%Y-%m-%d").date()
        except Exception:
            continue
        if ed == today:
            todays.append(f"- **{r['ticker']}** — earnings today ({r['next_earnings_date']}).")
        elif (ed - today).days == 1:
            todays.append(f"- **{r['ticker']}** — earnings tomorrow ({r['next_earnings_date']}).")

    if not todays:
        lines.append("- No tracked-universe earnings today or tomorrow on the calendar.")
    else:
        lines.extend(todays)

    fed = ((ms or {}).get("data", {}) or {}).get("fed", {}) or {}
    fomc = fed.get("next_fomc_date")
    if fomc:
        try:
            fd = datetime.strptime(fomc, "%Y-%m-%d").date()
            days = (fd - today).days
            if 0 <= days <= 3:
                lines.append(f"- **FOMC in {days}d** ({fomc}) — statement and press conference are the dominant macro catalyst.")
        except Exception:
            pass

    return "\n".join(lines)


def section5_closest_actionable(trigger: dict) -> str:
    records = trigger.get("records", []) if trigger else []
    actionable = [r for r in records if (r.get("action_state") or "").upper() in {"DEPLOYABLE", "ALMOST DEPLOYABLE"}]
    blocked    = [r for r in records if (r.get("action_state") or "").upper() == "BLOCKED"]
    do_not     = [r for r in records if (r.get("action_state") or "").upper() in {"DO NOT TOUCH", "BELOW STOP"}]

    lines = ["## 5) Closest actionable names\n"]

    if not actionable:
        lines.append("- No deployable or almost-deployable names on the live board.")
    else:
        for r in actionable:
            tk = r.get("ticker", "")
            close = r.get("close")
            eb = r.get("entry_band") or {}
            lo, hi = eb.get("low"), eb.get("high")
            band_label = eb.get("label", "no band")
            state = r.get("action_state", "")

            if lo is not None and hi is not None and close is not None:
                try:
                    c = float(close)
                    if c > float(hi):
                        d = c - float(hi)
                        pct = (d / float(hi)) * 100.0 if hi else 0.0
                        gap_str = f"+${d:,.2f} / +{pct:,.2f}% above {fmt(hi)}"
                    elif c < float(lo):
                        d = float(lo) - c
                        pct = (d / float(lo)) * 100.0 if lo else 0.0
                        gap_str = f"-${d:,.2f} / -{pct:,.2f}% below {fmt(lo)}"
                    else:
                        gap_str = "in band"
                except Exception:
                    gap_str = "—"
            else:
                gap_str = "no band"

            lines.append(f"- **{tk}** — {state}. Close {fmt(close)}, band {band_label}. Gap: {gap_str}.")

    if blocked:
        lines.append(f"\n**Blocked / not actionable now:**")
        for r in blocked:
            lines.append(f"- **{r['ticker']}** — {r.get('catalyst_blocker', 'blocked')}.")

    if do_not:
        lines.append(f"\n**Do not touch:**")
        for r in do_not:
            lines.append(f"- **{r['ticker']}** — {r.get('why', r.get('deployment_reason','impaired'))}.")

    return "\n".join(lines)


def section6_trigger_conditions(trigger: dict) -> str:
    records = trigger.get("records", []) if trigger else []
    actionable = [r for r in records if (r.get("action_state") or "").upper() in {"DEPLOYABLE", "ALMOST DEPLOYABLE"}]

    lines = ["## 6) Trigger conditions\n"]
    if not actionable:
        lines.append("- No active triggers on the board.")
        return "\n".join(lines)

    for r in actionable:
        tk = r.get("ticker", "")
        trig = r.get("technical_trigger") or "—"
        eb = r.get("entry_band") or {}
        band_label = eb.get("label", "no band")
        stop = r.get("invalidation")
        size = r.get("size_tier", "")
        lines.append(f"- **{tk}:** {trig} Band {band_label}. Stop {fmt(stop)}. Size: {size}.")

    return "\n".join(lines)


def section7_recommended_actions(trigger: dict, post_prep: dict, validation: dict) -> str:
    summary = trigger.get("summary", {}) or {}
    almost = summary.get("almost_deployable", []) or []
    blocked = summary.get("blocked", []) or []
    do_not = summary.get("do_not_touch", []) or []

    pkts = (post_prep or {}).get("packets", []) or []
    pre_earnings_imminent = [p["ticker"] for p in pkts if p.get("stage") == "imminent"]

    val_warnings = (validation or {}).get("warnings", []) or []
    band_warning = next((w for w in val_warnings if w.get("code") == "band_staleness"), None)

    lines = ["## 7) Recommended actions\n"]
    lines.append("### Do")
    if almost:
        lines.append(f"- Keep **{', '.join(almost)}** as the live conditional names. No chase above bands.")
    else:
        lines.append("- No active deploy candidates. Maintain discipline.")

    lines.append("\n### Watch")
    if blocked or pre_earnings_imminent:
        watch_set = sorted(set(blocked) | set(pre_earnings_imminent))
        lines.append(f"- **{', '.join(watch_set)}** — earnings-blocked / imminent prints. Prep post-earnings packets.")
    if band_warning:
        lines.append(f"- Band staleness warning active: {band_warning.get('message','')}")

    lines.append("\n### Avoid")
    if blocked:
        lines.append(f"- Do not override earnings blocks on **{', '.join(blocked)}**.")
    if do_not:
        lines.append(f"- Do not treat **{', '.join(do_not)}** as ready.")
    lines.append("- Do not chase any name extended above its band.")

    lines.append("\n### Open protocol")
    lines.append("- No discretionary new entries in the first 15–30 minutes unless a pre-set limit at a defined band already exists.")
    lines.append("- Prefer pullbacks into written bands over breakout chasing.")
    lines.append("- If the open is gap-driven and the name is still outside band, do nothing.")
    lines.append("- Re-check only if price actually reaches a written trigger zone.")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def render_markdown(today: date,
                    ms: dict, trigger: dict, validation: dict,
                    delta: dict | None, earnings: dict, post_prep: dict) -> str:
    last_td = ms.get("last_trading_day", "unknown") if ms else "unknown"
    gen_ts = datetime.now().strftime("%Y-%m-%d %H:%M")

    parts: list[str] = []
    parts.append(f"# Daily Executive Summary - {today.isoformat()}")
    parts.append(f"\n*Generated {gen_ts}. Data as of {last_td} close.*\n")
    parts.append(section1_bottom_line(trigger, validation, ms))
    parts.append("")
    parts.append(section2_execution_context(ms, validation))
    parts.append("")
    parts.append(section3_what_changed(delta))
    parts.append("")
    parts.append(section4_todays_catalysts(earnings, ms, today))
    parts.append("")
    parts.append(section5_closest_actionable(trigger))
    parts.append("")
    parts.append(section6_trigger_conditions(trigger))
    parts.append("")
    parts.append(section7_recommended_actions(trigger, post_prep, validation))
    parts.append("")
    parts.append("---\n")
    parts.append(f"*Auto-generated by `scripts/daily_executive_brief.py`. "
                 f"Inputs: market-state.json, trigger-sheet.json, technical-refresh.json, "
                 f"post-earnings-prep.json, dashboard-validation.json, dashboard-delta.json, "
                 f"earnings-calendar.json. A session-written brief, if present, takes precedence "
                 f"over this machine version.*")

    return "\n".join(parts)


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)

    today = date.today()

    ms        = load_json(MARKET_STATE) or {}
    trigger   = load_json(TRIGGER_SHEET) or {}
    validation = load_json(VALIDATION) or {}
    delta     = load_json(DELTA)
    earnings  = load_json(EARNINGS_CAL) or {}
    post_prep = load_json(POST_PREP) or {}

    md = render_markdown(today, ms, trigger, validation, delta, earnings, post_prep)

    canonical = OUT_DIR / f"{today.isoformat()}.md"
    machine   = OUT_DIR / f"{today.isoformat()}-machine.md"
    canonical_allowed, trust_reason = canonical_note_mutation_gate(validation)

    target = canonical if canonical_allowed else machine
    skipped_session = False
    if canonical_allowed and canonical.exists():
        existing = canonical.read_text(encoding="utf-8", errors="replace")
        if "Auto-generated by `scripts/daily_executive_brief.py`" not in existing:
            target = machine
            skipped_session = True

    atomic_write_text(target, md, encoding="utf-8")

    summary = {
        "generated_at_utc":   utc_now(),
        "brief_date":         today.isoformat(),
        "market_data_as_of":  ms.get("last_trading_day"),
        "confidence_grade":   confidence_grade(validation)[0],
        "canonical_mutation_allowed": canonical_allowed,
        "trust_reason":       trust_reason,
        "trust_gate_blocked": not canonical_allowed,
        "deployable_now":     (trigger.get("summary", {}) or {}).get("deployable_now", []),
        "almost_deployable":  (trigger.get("summary", {}) or {}).get("almost_deployable", []),
        "blocked":            (trigger.get("summary", {}) or {}).get("blocked", []),
        "deferred_to_machine": skipped_session,
        "wrote_to":           str(target.relative_to(WORKSPACE)),
    }
    atomic_write_json(OUT_JSON, summary, indent=2, ensure_ascii=True)

    sep = "=" * 60
    print(f"\n{sep}")
    print(f"  DAILY EXECUTIVE BRIEF  --  {today.isoformat()}")
    print(sep)
    print(f"  Confidence: {summary['confidence_grade']}")
    print(f"  Deployable now:    {len(summary['deployable_now'])}")
    print(f"  Almost deployable: {len(summary['almost_deployable'])}")
    print(f"  Blocked:           {len(summary['blocked'])}")
    if not canonical_allowed:
        print(f"  [!] Trust gate blocked canonical write; wrote machine sidecar instead.")
    elif skipped_session:
        print(f"  [!] Session-written brief detected at {canonical.name}; wrote machine sidecar instead.")
    print(f"  Wrote -> {summary['wrote_to']}")
    print(f"  Saved -> tmp/daily-executive-brief.json")
    print(sep + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
