"""weekly_macro_snapshot.py

Generate the Weekly Macro Snapshot from cached tmp/ artifacts.

Reads:
    tmp/market-state.json
    tmp/macro-metrics-current.json
    tmp/macro-judgment-draft.json
    tmp/regime-scores.json
    tmp/earnings-calendar.json

Writes:
    02. Markets/Weekly Macro Snapshot/YYYY-Www.md   (ISO week folder)
    tmp/weekly-macro-snapshot.json

Behavior:
    - Idempotent for the same ISO week.
    - Session-written files take precedence — if a hand-written file already
      exists at the canonical path, the script writes to YYYY-Www-machine.md.

Usage:
    python scripts/weekly_macro_snapshot.py
"""

from __future__ import annotations

import json
import argparse
import re
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from market_data_utils import atomic_write_json, atomic_write_text, fetch_treasury_auctions

WORKSPACE        = Path(__file__).resolve().parents[1]
MARKET_STATE     = WORKSPACE / "tmp" / "market-state.json"
MACRO_REGIME     = WORKSPACE / "tmp" / "macro-regime.json"
MACRO_METRICS    = WORKSPACE / "tmp" / "macro-metrics-current.json"
MACRO_JUDGMENT   = WORKSPACE / "tmp" / "macro-judgment-draft.json"
REGIME_SCORES    = WORKSPACE / "tmp" / "regime-scores.json"
EARNINGS_CAL     = WORKSPACE / "tmp" / "earnings-calendar.json"
VALIDATION       = WORKSPACE / "tmp" / "dashboard-validation.json"
DEPLOYMENT_SURFACE = WORKSPACE / "tmp" / "deployment-readiness-surface.json"
OUT_DIR          = WORKSPACE / "02. Markets" / "Weekly Macro Snapshot"
OUT_JSON         = WORKSPACE / "tmp" / "weekly-macro-snapshot.json"
OUT_FILL_PROMPT  = WORKSPACE / "tmp" / "weekly-macro-snapshot-judgment-fill.md"

PLACEHOLDER_NEEDLES = (
    "_[Fill",
    "_[Offensive / Defensive-neutral / Defensive",
)
PLACEHOLDER_RE = re.compile(r"_\[[^\]]+\]_", re.IGNORECASE)
UNRESOLVED_TERM_RE = re.compile(r"\b(TBD|TODO|FIXME|Fill:|Fill from|judgment placeholder)\b", re.IGNORECASE)
AUTO_MARKER = "Auto-generated by `scripts/weekly_macro_snapshot.py`"


def load_json(path: Path) -> dict | list | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"  WARNING: could not load {path.name}: {exc}")
        return None


def fmt(v: Any, decimals: int = 2, suffix: str = "") -> str:
    if v is None:
        return "N/A"
    try:
        return f"{float(v):,.{decimals}f}{suffix}"
    except Exception:
        return str(v)


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def source_age_note(as_of: Any, reference: Any, label: str) -> str | None:
    if not as_of or not reference:
        return f"{label} timestamp missing; treat as stale until refreshed."
    try:
        source_date = datetime.strptime(str(as_of), "%Y-%m-%d").date()
        ref_date = datetime.strptime(str(reference), "%Y-%m-%d").date()
    except Exception:
        return f"{label} timestamp not parseable; treat as stale until refreshed."
    if source_date < ref_date:
        return f"{label} is stale vs market-state date ({source_date.isoformat()} vs {ref_date.isoformat()}); use caveat."
    return None


def placeholder_count(text: str) -> int:
    broad_matches = PLACEHOLDER_RE.findall(text)
    without_bracket_placeholders = PLACEHOLDER_RE.sub("", text)
    terms = len(UNRESOLVED_TERM_RE.findall(without_bracket_placeholders))
    legacy = sum(text.count(n) for n in PLACEHOLDER_NEEDLES)
    return max(len(broad_matches), legacy) + terms


def authority_statement_present(text: str) -> bool:
    lower = text.lower()
    return all(
        term in lower
        for term in (
            "review-only",
            "no trade",
            "sizing",
            "account",
            "execution authority",
        )
    )


def dashboard_summary(validation: dict) -> tuple[int, int, str, dict]:
    summary = (validation or {}).get("summary") or {}
    freshness = (validation or {}).get("source_freshness") or {}
    try:
        critical = int(summary.get("critical", 0) or 0)
    except Exception:
        critical = 0
    try:
        warning = int(summary.get("warning", 0) or 0)
    except Exception:
        warning = 0
    overall = str((validation or {}).get("overall") or "").strip().lower()
    return critical, warning, overall, freshness


def validate_snapshot_markdown(
    md: str,
    validation: dict,
    deployment_surface: dict | None = None,
    market_state: dict | None = None,
    macro_regime: dict | None = None,
    macro_metrics: dict | None = None,
    macro_judgment: dict | None = None,
) -> dict[str, Any]:
    """Validate completion/readiness for the macro snapshot note itself.

    This is deliberately macro-specific. Dashboard warnings can block portfolio
    actions without blocking a completed macro note, but placeholders, source
    stop-lines, missing review-only authority text, or dashboard criticals must
    fail closed.
    """
    blockers: list[str] = []
    warnings: list[str] = []

    placeholders = placeholder_count(md)
    if placeholders:
        blockers.append(f"{placeholders} judgment placeholder(s) remain")
    if not authority_statement_present(md):
        blockers.append("review-only authority statement missing")

    critical, warning, overall, freshness = dashboard_summary(validation)
    if critical > 0:
        blockers.append(f"dashboard validation has {critical} critical issue(s)")
    if freshness.get("stop_line"):
        blockers.append("source freshness stop-line is active")
    if not freshness.get("presentation_allowed", False):
        blockers.append("source freshness does not allow presentation")
    if overall and overall not in {"ok", "clean", "warning"}:
        blockers.append(f"dashboard validation overall={overall}")
    if warning > 0:
        warnings.append(f"dashboard validation has {warning} warning(s); macro note may still be review-ready if blockers are clear")
    if freshness.get("capital_action_allowed") is not False:
        blockers.append("capital_action_allowed is not explicitly false")

    if market_state is not None:
        if (market_state or {}).get("status") != "ok":
            blockers.append("market-state status is not ok")
        if not (market_state or {}).get("generated_at_utc"):
            warnings.append("market-state generated_at_utc missing")
        market_data = (market_state or {}).get("data") or {}
        if ((market_data.get("fx") or {}).get("dxy")) is None:
            blockers.append("required macro input missing: DXY")
        credit_data = market_data.get("credit") or {}
        if credit_data.get("high_yield_oas") is None:
            blockers.append("required macro input missing: high-yield credit spread")
    if macro_regime is not None:
        if (macro_regime or {}).get("status") != "ok":
            blockers.append("macro-regime status is not ok")
        if not (macro_regime or {}).get("generated_at_utc"):
            warnings.append("macro-regime generated_at_utc missing")
    if macro_metrics is not None:
        if (macro_metrics or {}).get("status") not in {"ok", "warning"}:
            warnings.append("macro-metrics status is not ok/warning")
        metric_validation = (macro_metrics or {}).get("validation") or {}
        if metric_validation.get("status") != "ok":
            warnings.append("macro-metrics validation is not ok")
    if macro_judgment is not None:
        if (macro_judgment or {}).get("status") not in {"ok", "warning"}:
            warnings.append("macro-judgment status is not ok/warning")
        judgment_validation = (macro_judgment or {}).get("validation") or {}
        if judgment_validation.get("status") != "ok":
            warnings.append("macro-judgment validation is not ok")

    deployment_system = ((deployment_surface or {}).get("system") or {}) if deployment_surface is not None else {}
    if deployment_surface is not None and deployment_system:
        if deployment_system.get("stop_line"):
            blockers.append("deployment surface stop-line is active")
        if deployment_system.get("presentation_allowed") is False:
            warnings.append(
                "deployment surface presentation_allowed=false; treat deployment posture as degraded/review-only, not macro-note blocking when stop_line=false"
            )

    complete = not blockers
    return {
        "placeholder_count": placeholders,
        "placeholder_check_passed": placeholders == 0,
        "blockers": blockers,
        "warnings": warnings,
        "complete": complete,
        "macro_canonical_write_allowed": complete,
        "macro_canonical_write_reason": "macro snapshot complete and presentation gate clear" if complete else "; ".join(blockers),
        "source_gate": {
            "dashboard_critical": critical,
            "dashboard_warning": warning,
            "dashboard_presentation_allowed": bool(freshness.get("presentation_allowed", False)),
            "dashboard_stop_line": bool(freshness.get("stop_line", False)),
            "deployment_surface_presentation_allowed": deployment_system.get("presentation_allowed"),
            "deployment_surface_stop_line": deployment_system.get("stop_line"),
            "macro_metrics_status": (macro_metrics or {}).get("status") if macro_metrics is not None else None,
            "macro_judgment_status": (macro_judgment or {}).get("status") if macro_judgment is not None else None,
        },
        "authority": {
            "review_only_statement_present": authority_statement_present(md),
            "capital_action_allowed": freshness.get("capital_action_allowed"),
            "trade_execution_authorized": False,
            "canonical_mutation_allowed": False,
            "generated_macro_note_write_allowed": complete,
            "portfolio_mutation_allowed": False,
            "trade_execution_allowed": False,
            "owner_approval_granted": False,
        },
    }


def build_judgment_fill_prompt(label: str, machine_path: Path, validation_result: dict[str, Any]) -> str:
    blockers = validation_result.get("blockers") or []
    blocker_lines = "\n".join(f"- {b}" for b in blockers) or "- None"
    return f"""# Weekly Macro Snapshot Judgment Fill — {label}

Use this as the bounded Veritas/Randall completion layer for `{machine_path.as_posix()}`.

## Current completion blockers
{blocker_lines}

## Fill requirements
Replace every placeholder in the machine snapshot before treating the report as final:
- Inflation/growth: automated metrics are prefilled from `tmp/macro-metrics-current.json`; add judgment on momentum, acceleration/deceleration, and market implication.
- Energy/commodities: EIA inventory context if available, rig count if available, and a supply/demand/geopolitical-premium read.
- FX: one-sentence dollar read tying DXY to rates and risk appetite.
- Geopolitical flags: 2–4 current hot items with portfolio implications.
- Macro calendar: next-week CPI/PCE/GDP/jobless-claims/NFP/ISM/Fed events as applicable.
- Posture call: Offensive / Defensive-neutral / Defensive, with basis.
- One-line directive: concise review-only portfolio posture instruction.

## Required authority boundary
The completed note must retain: `Review-only. No trade, sizing, account, or execution authority.`

## Validation expectation
Do not promote or call the note final until `tmp/weekly-macro-snapshot.json` shows:
- `placeholder_count: 0`
- `placeholder_check_passed: true`
- `report_complete: true`
- `macro_canonical_write_allowed: true`
"""


def build_summary(
    label: str,
    monday: date,
    friday: date,
    ms: dict,
    snapshot_validation: dict[str, Any],
    target: Path,
    skipped_session: bool = False,
) -> dict[str, Any]:
    canonical_allowed = bool(snapshot_validation["macro_canonical_write_allowed"])
    trust_reason = str(snapshot_validation["macro_canonical_write_reason"])
    final_status = "complete" if snapshot_validation["complete"] else "blocked"
    if snapshot_validation["placeholder_count"]:
        final_status = "blocked_placeholders"
    return {
        "generated_at_utc":  utc_now(),
        "iso_week":          label,
        "week_start":        monday.isoformat(),
        "week_end":          friday.isoformat(),
        "market_data_as_of": ms.get("last_trading_day"),
        "canonical_mutation_allowed": False,
        "generated_macro_note_write_allowed": canonical_allowed,
        "portfolio_mutation_allowed": False,
        "trade_execution_allowed": False,
        "owner_approval_granted": False,
        "trust_reason":      trust_reason,
        "trust_gate_blocked": not canonical_allowed,
        "final_status": final_status,
        "placeholder_count": snapshot_validation["placeholder_count"],
        "placeholder_check_passed": snapshot_validation["placeholder_check_passed"],
        "report_complete": snapshot_validation["complete"],
        "macro_canonical_write_allowed": snapshot_validation["macro_canonical_write_allowed"],
        "macro_canonical_write_reason": snapshot_validation["macro_canonical_write_reason"],
        "completion_blockers": snapshot_validation["blockers"],
        "completion_warnings": snapshot_validation["warnings"],
        "source_gate": snapshot_validation.get("source_gate"),
        "authority": snapshot_validation.get("authority"),
        "deferred_to_machine": skipped_session,
        "validated_markdown_path": str(target.relative_to(WORKSPACE)) if target.is_relative_to(WORKSPACE) else str(target),
        "wrote_to":          str(target.relative_to(WORKSPACE)) if target.is_relative_to(WORKSPACE) else str(target),
        "judgment_fill_prompt": str(OUT_FILL_PROMPT.relative_to(WORKSPACE)),
    }


def iso_week_label(today: date) -> tuple[str, date, date]:
    """Return (label like '2026-W17', monday, friday)."""
    iso = today.isocalendar()
    label = f"{iso.year}-W{iso.week:02d}"
    monday = today - timedelta(days=today.weekday())
    friday = monday + timedelta(days=4)
    return label, monday, friday


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def build_regime_assessment(ms: dict, scores: dict, macro_regime: dict) -> str:
    data = (ms or {}).get("data", {}) or {}
    fed = data.get("fed", {}) or {}
    vol = data.get("volatility", {}) or {}
    eq = data.get("equities", {}) or {}
    fx = data.get("fx", {}) or {}
    en = data.get("energy", {}) or {}
    credit = data.get("credit", {}) or {}
    breadth = data.get("breadth", {}) or {}
    sectors = data.get("sectors", {}) or {}
    pillars = (macro_regime or {}).get("pillars", {}) or {}

    lines = ["## 1) Macro Regime Assessment\n"]
    regime = scores.get("scoring_regime") if scores else None
    lines.append(f"- **Operating regime:** {regime or 'late-cycle, restrictive-policy, selective risk-on (default framing)'}.")
    lines.append(f"- **SPX:** {fmt(eq.get('spx'))}  |  **VIX:** {fmt(vol.get('vix'))}  |  **DXY:** {fmt(fx.get('dxy'))}.")
    lines.append(f"- **Brent:** ${fmt(en.get('brent'))}  |  **WTI:** ${fmt(en.get('wti'))}.")
    lines.append(f"- **Fed target:** {fmt(fed.get('target_low'), 2)}%–{fmt(fed.get('target_high'), 2)}% "
                 f"(confirmed {fed.get('target_confirmed','n/a')}).")
    credit_label = ((pillars.get("credit") or {}).get("label") or "").strip()
    if credit_label:
        lines.append(f"- **Credit:** {credit_label}.")
    elif credit:
        lines.append(f"- **Credit:** HY OAS {fmt(credit.get('high_yield_oas'))}%, IG OAS {fmt(credit.get('investment_grade_oas'))}% "
                     f"({credit.get('stress_regime', 'n/a')}).")
    breadth_label = ((pillars.get("breadth") or {}).get("label") or "").strip()
    if breadth_label:
        lines.append(f"- **Breadth:** {breadth_label}.")
    elif breadth:
        lines.append(f"- **Breadth:** {breadth.get('sectors_above_50dma', 'n/a')}/11 sectors above 50DMA; "
                     f"{breadth.get('breadth_regime', 'n/a')}.")
    ranked_sectors = [s for s in sectors.values() if isinstance(s, dict) and s.get("relative_vs_spx_pct") is not None]
    if ranked_sectors:
        strongest = max(ranked_sectors, key=lambda s: s.get("relative_vs_spx_pct") or 0)
        weakest = min(ranked_sectors, key=lambda s: s.get("relative_vs_spx_pct") or 0)
        lines.append(f"- **Sector leadership vs SPY:** strongest {strongest.get('ticker', 'n/a')} "
                     f"({fmt(strongest.get('relative_vs_spx_pct'), 1, '%')}); weakest {weakest.get('ticker', 'n/a')} "
                     f"({fmt(weakest.get('relative_vs_spx_pct'), 1, '%')}).")
    return "\n".join(lines)


def build_fed_and_rates(ms: dict) -> str:
    data = (ms or {}).get("data", {}) or {}
    tr = data.get("treasuries", {}) or {}
    fed = data.get("fed", {}) or {}

    lines = ["## 2) Fed and Rates\n"]
    lines.append(f"- **2Y Treasury:** {fmt(tr.get('2y'), 3)}% as of {tr.get('2y_as_of', 'n/a')} ({tr.get('2y_source','')}).")
    lines.append(f"- **10Y Treasury:** {fmt(tr.get('10y'), 3)}% as of {tr.get('10y_as_of', 'n/a')} ({tr.get('10y_source','')}).")
    lines.append(f"- **3M T-bill:** {fmt(tr.get('3m_tbill'), 3)}% as of {tr.get('3m_as_of', 'n/a')} ({tr.get('3m_source','')}).")
    lines.append(f"- **2s10s spread:** {fmt(tr.get('curve_2s10s_bps'), 1)} bps.")
    lines.append(f"- **3M-10Y spread:** {fmt(tr.get('curve_3m10y_bps'), 1)} bps.")

    fomc_date = fed.get("next_fomc_date")
    cut_prob = fed.get("cut_probability_next_meeting")
    if fomc_date:
        cut_str = f"{cut_prob:.0f}% cut probability" if cut_prob is not None else "FedWatch unwired"
        lines.append(f"- **Next FOMC:** {fomc_date} — {cut_str}.")
    if fed.get("manual_update_required"):
        lines.append(f"- *Manual maintenance:* Fed target hardcoded; update after each FOMC decision.*")
    return "\n".join(lines)


def build_inflation_growth() -> str:
    """No live machine feed — emit explicit stub for human/AI completion."""
    return ("## 3) Inflation and Growth Pulse\n\n"
            "- **CPI / PCE / GDP (judgment):** _[Fill from latest BLS / BEA prints. "
            "Most recent CPI, PCE, and GDP advance estimates with YoY and MoM context.]_\n"
            "- **Labor (judgment):** _[Fill: NFP, jobless claims, unemployment rate trend.]_\n"
            "- **Pulse read:** _[Fill: is growth/inflation momentum accelerating, decelerating, or stable?]_")


def macro_metric_by_key(macro_metrics: dict, key: str) -> dict[str, Any]:
    rows = macro_metrics.get("metrics") if isinstance(macro_metrics, dict) else []
    if not isinstance(rows, list):
        return {}
    for row in rows:
        if isinstance(row, dict) and row.get("key") == key:
            return row
    return {}


def macro_metric_line(row: dict[str, Any], fields: tuple[str, ...] = ("mom_pct", "yoy_pct")) -> str:
    if not row or row.get("status") != "ok":
        label = (row or {}).get("name") or "metric"
        return f"{label} unavailable"
    parts = [f"{row.get('latest_value', 'n/a')} as of {row.get('latest_date', 'n/a')}"]
    labels = {
        "mom_pct": "MoM",
        "qoq_annualized_pct": "QoQ annualized",
        "yoy_pct": "YoY",
        "delta": "delta",
    }
    for field in fields:
        value = row.get(field)
        if value is None:
            continue
        suffix = "%" if field.endswith("_pct") else ""
        parts.append(f"{labels.get(field, field)} {fmt(value, 3, suffix)}")
    return "; ".join(parts)


def macro_judgment_text(macro_judgment: dict, key: str, fallback: str) -> str:
    judgments = macro_judgment.get("judgments") if isinstance(macro_judgment, dict) else {}
    if not isinstance(judgments, dict):
        return fallback
    row = judgments.get(key)
    if not isinstance(row, dict):
        return fallback
    text = str(row.get("text") or "").strip()
    return text or fallback


def build_inflation_growth_from_metrics(macro_metrics: dict, macro_judgment: dict) -> str:
    status = (macro_metrics or {}).get("status") or "missing"
    validation = ((macro_metrics or {}).get("validation") or {}).get("status") or "missing"
    cpi = macro_metric_by_key(macro_metrics, "cpi_headline")
    core_cpi = macro_metric_by_key(macro_metrics, "cpi_core")
    ppi = macro_metric_by_key(macro_metrics, "ppi_headline_final_demand")
    pce = macro_metric_by_key(macro_metrics, "pce_headline")
    core_pce = macro_metric_by_key(macro_metrics, "pce_core")
    gdp = macro_metric_by_key(macro_metrics, "real_gdp")
    unemployment = macro_metric_by_key(macro_metrics, "unemployment_rate")
    payrolls = macro_metric_by_key(macro_metrics, "nonfarm_payrolls")
    wages = macro_metric_by_key(macro_metrics, "average_hourly_earnings")
    initial_claims = macro_metric_by_key(macro_metrics, "initial_claims")
    continuing_claims = macro_metric_by_key(macro_metrics, "continuing_claims")
    ism = macro_metric_by_key(macro_metrics, "ism_manufacturing_pmi")

    lines = ["## 3) Inflation and Growth Pulse\n"]
    lines.append(f"- **Metrics source gate:** `tmp/macro-metrics-current.json` status `{status}`, validation `{validation}`.")
    lines.append(f"- **CPI:** headline {macro_metric_line(cpi)}; core {macro_metric_line(core_cpi)}.")
    lines.append(f"- **PPI:** final demand {macro_metric_line(ppi)}.")
    lines.append(f"- **PCE:** headline {macro_metric_line(pce)}; core {macro_metric_line(core_pce)}.")
    lines.append(f"- **GDP:** real GDP {macro_metric_line(gdp, ('qoq_annualized_pct', 'yoy_pct'))}.")
    lines.append(
        f"- **Labor:** unemployment {macro_metric_line(unemployment, ('delta',))}; "
        f"nonfarm payrolls {macro_metric_line(payrolls, ('delta',))}; "
        f"average hourly earnings {macro_metric_line(wages)}."
    )
    lines.append(
        f"- **Claims:** initial {macro_metric_line(initial_claims, ('delta',))}; "
        f"continuing {macro_metric_line(continuing_claims, ('delta',))}."
    )
    lines.append(f"- **ISM manufacturing:** {macro_metric_line(ism, ('delta',))}.")
    lines.append(f"- **Pulse read (judgment draft):** {macro_judgment_text(macro_judgment, 'pulse_read', 'Macro judgment draft unavailable; interpret manually before final use.')}")
    return "\n".join(lines)


def build_energy_commodities(ms: dict, macro_judgment: dict) -> str:
    data = (ms or {}).get("data", {}) or {}
    en = data.get("energy", {}) or {}
    reference_date = (ms or {}).get("last_trading_day")
    brent_note = source_age_note(en.get("brent_as_of"), reference_date, "Brent")
    wti_note = source_age_note(en.get("wti_as_of"), reference_date, "WTI")
    lines = ["## 4) Energy and Commodities\n"]
    lines.append(f"- **Brent:** ${fmt(en.get('brent'))} as of {en.get('brent_as_of', 'n/a')} ({en.get('brent_source','')}).")
    lines.append(f"- **WTI:** ${fmt(en.get('wti'))} as of {en.get('wti_as_of', 'n/a')} ({en.get('wti_source','')}).")
    if brent_note or wti_note:
        lines.append(f"- **Oil freshness caveat:** {'; '.join(note for note in (brent_note, wti_note) if note)}")
    try:
        spread = float(en.get("brent")) - float(en.get("wti"))
        lines.append(f"- **Brent/WTI spread:** ${spread:,.2f}.")
    except Exception:
        pass
    lines.append(f"- **EIA inventory (judgment draft):** {macro_judgment_text(macro_judgment, 'eia_inventory', 'EIA inventory artifact unavailable; manual review required.')}")
    lines.append(f"- **Rig count (judgment draft):** {macro_judgment_text(macro_judgment, 'rig_count', 'Rig-count artifact unavailable; manual review required.')}")
    lines.append(f"- **Energy structure read:** {macro_judgment_text(macro_judgment, 'energy_structure', 'Energy structure judgment unavailable; manual review required.')}")
    return "\n".join(lines)


def build_fx(ms: dict, macro_judgment: dict) -> str:
    data = (ms or {}).get("data", {}) or {}
    fx = data.get("fx", {}) or {}
    lines = ["## 5) FX\n"]
    lines.append(f"- **DXY:** {fmt(fx.get('dxy'))} as of {fx.get('as_of', 'n/a')} ({fx.get('source','')}).")
    lines.append(f"- **Dollar read (judgment draft):** {macro_judgment_text(macro_judgment, 'dollar_read', 'Dollar/rates judgment unavailable; manual review required.')}")
    return "\n".join(lines)


def build_geopolitical_flags() -> str:
    return ("## 6) Geopolitical Flags\n\n"
            "- **Tariff/trade risk flag:** manual review required after U.S.-China / tariff-policy headlines; do not treat trade-risk as clear unless sourced in the judgment fill.\n"
            "- **Hot items (judgment):** _[Fill from latest WIB or news sweep — Iran/Hormuz, Russia/Ukraine, "
            "China/Taiwan posture, sanctions, election cycles.]_\n"
            "- **Portfolio implication:** _[Fill: which tracked names have material exposure?]_")


def build_geopolitical_flags_from_judgment(macro_judgment: dict) -> str:
    return ("## 6) Geopolitical Flags\n\n"
            "- **Tariff/trade risk flag:** manual review required after U.S.-China / tariff-policy headlines; do not treat trade-risk as clear unless sourced in the judgment draft.\n"
            f"- **Hot items (judgment draft):** {macro_judgment_text(macro_judgment, 'geopolitical_hot_items', 'Live geopolitical/news sweep artifact unavailable; manual review required.')}\n"
            f"- **Portfolio implication:** {macro_judgment_text(macro_judgment, 'portfolio_implication', 'Portfolio implication judgment unavailable; manual review required.')}")


def build_key_events_next_week(earnings: dict, ms: dict, week_start: date, week_end: date, macro_judgment: dict) -> str:
    lines = ["## 7) Key Events Next Week\n"]
    next_monday = week_end + timedelta(days=3)  # Monday after this Friday
    next_friday = next_monday + timedelta(days=4)

    lines.append(f"*Window: {next_monday.isoformat()} → {next_friday.isoformat()}*\n")
    auctions = fetch_treasury_auctions(next_monday.isoformat(), next_friday.isoformat())
    lines.append("**Treasury auctions (official FiscalData):**")
    if auctions.get("status") == "ok" and auctions.get("auctions"):
        for row in auctions.get("auctions", [])[:12]:
            amount = row.get("offering_amt") or "amount n/a"
            lines.append(f"  - {row.get('auction_date')} — {row.get('security_term')} {row.get('security_type')} ({amount})")
    elif auctions.get("status") == "ok":
        lines.append("  - No Treasury auctions returned for the next-week window.")
    else:
        lines.append(f"  - Manual review required: {auctions.get('warning') or 'Treasury auction feed unavailable'}")

    next_week_earnings: list[str] = []
    for r in (earnings or {}).get("records", []):
        if r.get("error") or not r.get("next_earnings_date"):
            continue
        try:
            ed = datetime.strptime(r["next_earnings_date"], "%Y-%m-%d").date()
        except Exception:
            continue
        if next_monday <= ed <= next_friday:
            next_week_earnings.append(f"  - **{r['ticker']}** — {r['next_earnings_date']}")

    if next_week_earnings:
        lines.append("**Earnings (tracked universe):**")
        lines.extend(next_week_earnings)
    else:
        lines.append("- No tracked-universe earnings in next week's window.")

    fed = ((ms or {}).get("data", {}) or {}).get("fed", {}) or {}
    fomc = fed.get("next_fomc_date")
    if fomc:
        try:
            fd = datetime.strptime(fomc, "%Y-%m-%d").date()
            if next_monday <= fd <= next_friday:
                lines.append(f"\n**FOMC:** {fomc} — statement and press conference next week.")
        except Exception:
            pass

    lines.append(f"\n**Macro data (judgment draft):** {macro_judgment_text(macro_judgment, 'next_week_macro_data', 'Macro event judgment unavailable; manual review required.')}")
    return "\n".join(lines)


def build_regime_posture(scores: dict, deployment_surface: dict, macro_regime: dict) -> str:
    lines = ["## 8) Regime Posture and Portfolio Implication\n"]
    if scores and scores.get("records"):
        top = sorted(scores["records"], key=lambda r: -(r.get("total") or 0))[:5]
        lines.append("**Top 5 names by regime score:**")
        for r in top:
            lines.append(f"  - **{r['ticker']}** — {r.get('total','-')}/20  ({r.get('stance','')})")
    else:
        lines.append("- No regime scores available.")

    summary = (deployment_surface or {}).get("summary", {}) or {}
    groups = (deployment_surface or {}).get("groups", {}) or {}
    if summary:
        d = groups.get("DEPLOYABLE NOW") or []
        a = (groups.get("ALMOST DEPLOYABLE") or []) + (groups.get("ALMOST / NEAR-EARNINGS CAUTION") or [])
        b = (groups.get("BLOCKED") or []) + (groups.get("DO NOT TOUCH") or [])
        lines.append("")
        lines.append(f"**Deployment posture (machine):** {len(d)} deployable / {len(a)} almost / {len(b)} blocked.")
        for label, records in (("Deployable", d[:3]), ("Almost", a[:5]), ("Blocked/Do-not-touch", b[:5])):
            if records:
                tickers = ", ".join(r.get("ticker", "?") for r in records if isinstance(r, dict))
                lines.append(f"  - **{label}:** {tickers}")

    regime_label = ((macro_regime or {}).get("regime") or {}).get("label")
    if regime_label:
        lines.append(f"\n**Regime basis (machine):** {regime_label}.")

    lines.append("\n**Posture call (judgment):** _[Offensive / Defensive-neutral / Defensive — state basis]_.")
    lines.append("**One-line directive (judgment):** _[Fill]_.")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def build_regime_posture_from_judgment(scores: dict, deployment_surface: dict, macro_regime: dict, macro_judgment: dict) -> str:
    text = build_regime_posture(scores, deployment_surface, macro_regime)
    marker = "\n**Posture call (judgment):**"
    if marker in text:
        text = text.split(marker, 1)[0].rstrip()
    return "\n".join(
        [
            text,
            "",
            f"**Posture call (judgment draft):** {macro_judgment_text(macro_judgment, 'posture_call', 'Posture judgment unavailable; manual review required.')}",
            f"**One-line directive (judgment draft):** {macro_judgment_text(macro_judgment, 'one_line_directive', 'Directive judgment unavailable; manual review required.')}",
        ]
    )


def render_markdown(today: date, ms: dict, scores: dict, earnings: dict, macro_regime: dict, deployment_surface: dict, macro_metrics: dict, macro_judgment: dict) -> str:
    label, monday, friday = iso_week_label(today)
    last_td = ms.get("last_trading_day", "unknown") if ms else "unknown"
    gen_ts = datetime.now().strftime("%Y-%m-%d %H:%M")

    parts: list[str] = []
    parts.append(f"# Weekly Macro Snapshot — {label}")
    parts.append(f"\n*Window: {monday.isoformat()} → {friday.isoformat()}. "
                 f"Generated {gen_ts}. Data as of {last_td}.*\n")
    parts.append("**Authority:** Review-only. No trade, sizing, account, or execution authority.\n")
    parts.append(build_regime_assessment(ms, scores, macro_regime))
    parts.append("")
    parts.append(build_fed_and_rates(ms))
    parts.append("")
    parts.append(build_inflation_growth_from_metrics(macro_metrics, macro_judgment))
    parts.append("")
    parts.append(build_energy_commodities(ms, macro_judgment))
    parts.append("")
    parts.append(build_fx(ms, macro_judgment))
    parts.append("")
    parts.append(build_geopolitical_flags_from_judgment(macro_judgment))
    parts.append("")
    parts.append(build_key_events_next_week(earnings, ms, monday, friday, macro_judgment))
    parts.append("")
    parts.append(build_regime_posture_from_judgment(scores, deployment_surface, macro_regime, macro_judgment))
    parts.append("")
    parts.append("---\n")
    parts.append(f"*Auto-generated by `scripts/weekly_macro_snapshot.py`. "
                 f"Inputs: market-state.json (as of {last_td}), regime-scores.json, "
                 f"macro-regime.json, macro-metrics-current.json, macro-judgment-draft.json, "
                 f"deployment-readiness-surface.json, earnings-calendar.json. "
                 f"Sections marked _judgment draft_ are review-only and require final judgment before capital action.*")
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or validate the Weekly Macro Snapshot.")
    parser.add_argument("--validate", metavar="MARKDOWN", help="validate a completed snapshot without regenerating or overwriting it")
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)

    today = date.today()
    label, monday, friday = iso_week_label(today)

    ms       = load_json(MARKET_STATE) or {}
    macro_regime = load_json(MACRO_REGIME) or {}
    scores   = load_json(REGIME_SCORES) or {}
    earnings = load_json(EARNINGS_CAL) or {}
    validation = load_json(VALIDATION) or {}
    deployment_surface = load_json(DEPLOYMENT_SURFACE) or {}
    macro_metrics = load_json(MACRO_METRICS) or {}
    macro_judgment = load_json(MACRO_JUDGMENT) or {}

    if args.validate:
        input_path = Path(args.validate)
        if not input_path.is_absolute():
            input_path = WORKSPACE / input_path
        if not input_path.exists():
            print(f"ERROR: validation input not found: {input_path}")
            return 2
        md = input_path.read_text(encoding="utf-8", errors="replace")
        snapshot_validation = validate_snapshot_markdown(md, validation, deployment_surface, ms, macro_regime, macro_metrics, macro_judgment)
        summary = build_summary(label, monday, friday, ms, snapshot_validation, input_path)
        atomic_write_json(OUT_JSON, summary, indent=2)
        sep = "=" * 60
        print(f"\n{sep}")
        print(f"  WEEKLY MACRO SNAPSHOT VALIDATION  --  {label}")
        print(sep)
        print(f"  Input -> {summary['validated_markdown_path']}")
        print(f"  Complete -> {summary['report_complete']}")
        if summary["completion_blockers"]:
            print(f"  Blockers -> {'; '.join(summary['completion_blockers'])}")
        print(f"  Saved -> tmp/weekly-macro-snapshot.json")
        print(sep + "\n")
        return 0 if snapshot_validation["complete"] else 1

    md = render_markdown(today, ms, scores, earnings, macro_regime, deployment_surface, macro_metrics, macro_judgment)
    snapshot_validation = validate_snapshot_markdown(md, validation, deployment_surface, ms, macro_regime, macro_metrics, macro_judgment)

    canonical = OUT_DIR / f"{label}.md"
    machine   = OUT_DIR / f"{label}-machine.md"

    canonical_allowed = bool(snapshot_validation["macro_canonical_write_allowed"])
    trust_reason = str(snapshot_validation["macro_canonical_write_reason"])

    target = canonical if canonical_allowed else machine
    skipped_session = False
    preserved_machine = False
    if canonical_allowed and canonical.exists():
        existing = canonical.read_text(encoding="utf-8", errors="replace")
        if AUTO_MARKER not in existing:
            target = machine
            skipped_session = True
    if target == machine and machine.exists():
        existing = machine.read_text(encoding="utf-8", errors="replace")
        if AUTO_MARKER not in existing or placeholder_count(existing) == 0:
            target = OUT_DIR / f"{label}-machine-refresh.md"
            skipped_session = True
            preserved_machine = True

    atomic_write_text(target, md, encoding="utf-8")
    atomic_write_text(
        OUT_FILL_PROMPT,
        build_judgment_fill_prompt(label, target.relative_to(WORKSPACE), snapshot_validation),
        encoding="utf-8",
    )

    summary = build_summary(label, monday, friday, ms, snapshot_validation, target, skipped_session)
    summary["preserved_existing_machine_sidecar"] = preserved_machine
    atomic_write_json(OUT_JSON, summary, indent=2)

    sep = "=" * 60
    print(f"\n{sep}")
    print(f"  WEEKLY MACRO SNAPSHOT  --  {label}")
    print(sep)
    print(f"  Window: {monday.isoformat()} -> {friday.isoformat()}")
    print(f"  Data as of: {summary['market_data_as_of']}")
    if not canonical_allowed:
        print(f"  [!] Macro completion gate blocked canonical write; wrote machine sidecar instead.")
        print(f"      Reason: {trust_reason}")
    elif skipped_session:
        print(f"  [!] Session-written file at {canonical.name}; wrote machine sidecar.")
    if preserved_machine:
        print(f"  [!] Existing machine sidecar looked completed or human-owned; preserved it and wrote refresh sidecar.")
    print(f"  Wrote -> {summary['wrote_to']}")
    print(f"  Fill -> {summary['judgment_fill_prompt']}")
    print(f"  Saved -> tmp/weekly-macro-snapshot.json")
    print(sep + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
